### ISSUE TITLE
gui/collada_dom is missing osdeps

### ISSUE THREAD

**Issue by planthaber** [rock-core/rock-package_set#101]
```
In file included from /data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/master/node/Debian_stable/dev/gui/collada_dom/dom/src/dae/daeIOPluginCommon.cpp:18:0:
      /data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/master/node/Debian_stable/dev/gui/collada_dom/dom/include/dae/daeZAEUncompressHandler.h:12:19: fatal error: unzip.h: No such file or directory
       #include <unzip.h>
```

**Comment by doudou** [comment]
collada_dom bundles its dependencies. I personally don't have unzip.h but it compiles fine. My guess would be that unzip.h is present on the build system, detected by collada_dom which then does *not* build the bundled minizip and finally does not manage to find unzip.h at compile time.

**Comment by 2maz** [comment]
collada_dom searches for minizip via pkg-config and when already installed (external/minizip mostly due to mars simulation) the include dir is: /rock/install/include/. So while the include refers to <unzip>, unzip.h resides in /rock/install/include/minizip/.

**Comment by doudou** [comment]
> unzip.h resides in /rock/install/include/minizip/.

the patched minizip from rock-simulation does things differently than the original package. libminizip-dev (from ubuntu) does install in minizip/ but adds -I/usr/include/minizip to the cflags in the pkg-config.

**Comment by 2maz** [comment]
Open issue on to move discussion to correct package set rock-simulation/simulation-package_set#26
