### ISSUE TITLE
Why are there two orogen components for the dynamixel?

### ISSUE THREAD

**Issue by Rauldg** [rock-core/rock-package_set#162]
Is there any difference? Should both be kept?

1: https://github.com/rock-core/rock-package_set/blob/master/orogen.autobuild#L82
https://github.com/rock-drivers/drivers-orogen-servo_dynamixel

2: https://github.com/rock-core/rock-package_set/blob/master/orogen.autobuild#L100
https://github.com/rock-drivers/drivers-orogen-dynamixel

**Comment by doudou** [comment]
As far as I remember, `servo_dynamixel` uses the new dynamixel protocol and `dynamixel` the old one. I don't know more than that, though ...
