### ISSUE TITLE
linked source for external/aruco does not exist anymore

### ISSUE THREAD

**Issue by Kynneb** [rock-core/rock-package_set#193]
As in the title. It seems the version does not exist anymore and only version aruco-1.3.0.tgz is available.

**Comment by Rauldg** [comment]
On this [branch](https://github.com/rock-core/rock-package_set/tree/aruco_v2) you get Aruco v2 built from sources. The repository is not the official one of the developers (they don't provide one).

I think that is the reason why the aruco_v2 branch does not get merged to master ... Or maybe someone was working on merging an even newer version? 

@2maz

**Comment by 2maz** [comment]
Fixed by moving to aruco 3.1 #209
