### ISSUE TITLE
Aravis broken patch

### ISSUE THREAD

**Issue by Rauldg** [rock-core/rock-package_set#197]
Hi,

there is a patch that is outdated for `drivers/aravis`. There is also a branch in this repository that removes this failing [patch](https://github.com/rock-core/rock-package_set/commit/d33fca5acea5b9e9c03cdb3b9e238198ad8077a0). 

Can we merge the branch that removes the patch into master?

@2maz

**Comment by Rauldg** [comment]
Actually, the patch is not removed on the branch, only not applied. The patch should be removed to IMO.

**Comment by Rauldg** [comment]
Without the patch, the library does not build. With the patch, Autoproj can not even check it out.

We should either:
- Update the build instructions for that package have to be updated.
or 
- Set the source to a particular commit, instead of to the master head.

**Comment by 2maz** [comment]
Could you check after pinning to 0.6.3 -- looks like they changed the build system
https://github.com/AravisProject/aravis/tree/ARAVIS_0_6_3

**Comment by Rauldg** [comment]
It builds on that tag. [Here is the PR](https://github.com/rock-core/rock-package_set/pull/198)

**Comment by Rauldg** [comment]
@2maz I will close the issue. I think that it is so far fine to leave the package fixed. At least until we need the latest changes.
