### ISSUE TITLE
control/urdfdom fails to build since most recent updates

### ISSUE THREAD

**Issue by moooeeeep** [rock-core/rock-package_set#241]
Our CI spotted the package control/urdfdom doesn't build anymore, since the most recent updates to the package.

We pinned it to this version to make it build again:

    - control/urdfdom:
      commit: 99c6f58120a5dfd1f9fc36419cd9f9aa0246efde

---

Steps to reproduce:

* set up clean workspace
* add this manifest:

      package_sets:
       - github: rock-core/rock-package_set
      layout:
       - control/urdfdom

---

Error message:

    [ 82%] Linking CXX executable ../bin/check_urdf
    ../lib/liburdfdom_model.so.1.0: Warnung: undefinierter Verweis auf »base::logging::Logger::log(base::logging::Priority, char const*, char const*, int, char const*, char const*, ...) const«
    ../lib/liburdfdom_model.so.1.0: Warnung: undefinierter Verweis auf »base::logging::Logger::Logger()«
    collect2: error: ld returned 1 exit status
    urdf_parser/CMakeFiles/check_urdf.dir/build.make:97: recipe for target 'bin/check_urdf' failed
    make[2]: *** [bin/check_urdf] Error 1
    CMakeFiles/Makefile2:837: recipe for target 'urdf_parser/CMakeFiles/check_urdf.dir/all' failed
    make[1]: *** [urdf_parser/CMakeFiles/check_urdf.dir/all] Error 2
    Makefile:140: recipe for target 'all' failed
    make: *** [all] Error 2

**Comment by doudou** [comment]
Just noticed as well ... was away from coding for a few days

https://github.com/rock-core/base-console_bridge/pull/6 should be fixing this
