### ISSUE TITLE
Move opaque_autogen to rock-core 

### ISSUE THREAD

**Issue by annaborn** [rock-core/rock-package_set#250]
Hello guys!

Can we move https://github.com/dfki-ric/slam-opaque_autogen from dfki-ric group into rock-core group? Better would be under tools-opaque_autogen. Since it has nothing with slam, it is general plugin for orogen. :) Plus add it into rock_package_set.

Currently we have problem, that this package is not a part of any public package set and is defined only in our private package set. However, our public envire depends on it. 

https://github.com/envire/envire-orogen-envire_core/blob/master/manifest.xml

Thank you in advance!

@doudou @planthaber @skasperski

**Comment by skasperski** [comment]
If we decide to put it into tools, we should probably change the repository name in that go as well, preferably just "opaque_autogen" without the "slam-" prefix.

**Comment by planthaber** [comment]
I created a fork in https://github.com/rock-core/tools-orogen_opaque_autogen.

It should be the only fork of the repo, if you delete the [https://github.com/dfki-ric/slam-opaque_autoge](https://github.com/dfki-ric/slam-opaque_autogen) repo later, the new location becomes the master repo

Please add it to the rock-core package set, but with "remove_from_default", so it is only installed when needed and not as part of rock.core in the manifest. 

Don't forget to update the dependency definitions in packages using it.
