### ISSUE TITLE
remove aria package from rock

### ISSUE THREAD

**Issue by goldhoorn** [rock-core/rock-package_set#61]
@christian-rauch:
Please can you find a better location for the aria package:

https://github.com/rock-core/rock-package_set/blob/master/source.yml#L197
The rock-website should not host this because it might be auto-generated in the long run.
Either move the driver into the orogen component if the licence allows this, change the link to a public other one, or handle the package simliar to the ids cameras...

**Comment by christian-rauch** [comment]
Moved to public mobile robots server by PR #62

**Comment by goldhoorn** [comment]
Fixed, thanks for contributing
