### ISSUE TITLE
Apriltags marker detector repository

### ISSUE THREAD

**Issue by dbcesar** [rock-core/rock-package_set#71]
Hi,

I would like to add Apriltags marker detector to the rock-core package set in "perception/apriltags" and "perception/orogen/apriltags".

Currently the orogen component is available in my personal repository dbcesar/perception-orogen-apriltags, so could someone create a git repository where I can push my code? 
The library installation method is via archive available in http://april.eecs.umich.edu/wiki/index.php/AprilTags

So, after I pushed my code to the created repository, I'm gonna create a pull request here to add both, the library and my component. 

Thanks

**Comment by doudou** [comment]
Created https://github.com/rock-perception/perception-apriltags and https://github.com/rock-perception/perception-orogen-apriltags, and added you to the Maintainers team. Have a nice day !
