### ISSUE TITLE
current libs.autobuild is not compatible with autobuild v. 1.9.3

### ISSUE THREAD

**Issue by D-Alex** [rock-core/rock-package_set#94]
env_add_path seems to be a method of autobuild 1.10.0.x
https://github.com/rock-core/rock-package_set/blob/1f6d7100618d5a31309787b9f1761361bcbf911e/libs.autobuild#L121

**Comment by doudou** [comment]
Package#env_add_path is indeed 1.10+ .... Just replace by Autoproj.env_add_path

**Comment by doudou** [comment]
Could you check #95 out ?
